# Artificial Neural Network

### Importing the libraries

In [25]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [26]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [27]:
dataset = pd.read_excel('myxl.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [28]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [29]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

If you don't mention the random_state in the code, then whenever you execute your code a new random value is generated and the train and test datasets would have different values each time.

## Part 2 - Building the ANN

### Initializing the ANN

In [31]:
ann=tf.keras.models.Sequential()


### Adding the input layer and the first hidden layer

In [32]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

1)Dense class create fully connected layers between input layers and first hidden layer
2)units is no of newrons in first hidden layer

### Adding the second hidden layer

In [33]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [34]:
ann.add(tf.keras.layers.Dense(units=1))

here we do regression problem so no need of activation  function .in classification problem we need to add activation function like sigmoid act fun for 2 class prediction and if your class is more than 2 that we use softmax act fun .

## Part 3 - Training the ANN

### Compiling the ANN

In [35]:
ann.compile(optimizer='adam',loss='mean_squared_error')

1)optimizer is a tool for performing SGD.(here we use 'adam' optimizer).
2)loss parater takes loss function which is 'mean_squared_error' here because it's a regression problem.


### Training the ANN model on the Training set

In [37]:
ann.fit(x=X_train,y=y_train,batch_size=32,epochs=50)

Epoch 1/50
240/240 [==============================] - 0s 990us/step - loss: 26.6134
Epoch 2/50
240/240 [==============================] - 0s 988us/step - loss: 27.0896
Epoch 3/50
240/240 [==============================] - 0s 910us/step - loss: 26.8160
Epoch 4/50
240/240 [==============================] - 0s 966us/step - loss: 26.9028
Epoch 5/50
240/240 [==============================] - 0s 924us/step - loss: 27.1377
Epoch 6/50
240/240 [==============================] - 0s 1ms/step - loss: 27.1455
Epoch 7/50
240/240 [==============================] - 0s 950us/step - loss: 26.4736
Epoch 8/50
240/240 [==============================] - 0s 989us/step - loss: 26.9549
Epoch 9/50
240/240 [==============================] - 0s 972us/step - loss: 26.6382
Epoch 10/50
240/240 [==============================] - 0s 934us/step - loss: 26.6875
Epoch 11/50
240/240 [==============================] - 0s 973us/step - loss: 27.5984
Epoch 12/50
240/240 [==============================] - 0s 1ms/step - loss: 2

### Predicting the results of the Test set

In [39]:
y_pred=ann.predict(X_test)

**check model performance**

In [40]:
np.set_printoptions(precision=2)#to set 2 no after decimal

In [52]:
 a1=y_pred.reshape(len(y_pred),1)
 a2=y_test.reshape(len(y_test),1)
 np.concatenate((a1,a2),1)

array([[431.31, 431.23],
       [462.46, 460.01],
       [465.98, 461.14],
       ...,
       [473.22, 473.26],
       [439.92, 438.  ],
       [459.19, 463.28]])

1.   numpy reshape to reshap in 1 column
2.   in concatenate function pass arrays as a tuple (important) 





In [43]:
y_pred

array([[431.31],
       [462.46],
       [465.98],
       ...,
       [473.22],
       [439.92],
       [459.19]], dtype=float32)